User Authentication done in Django by making register and login pages
musanaeem/Django-First-Project pull request #2
Opened 2022-08-18 14:24 UTC by musanaeem

Created a User Authentication mechanism on Django using templates of login and signup page (HTML/CSS) online. The user is added into the User database on signup and authenticated in sign in. Functions are made in views.py in the profiles folder.

2022-08-22 07:54 UTC, srehaider requested changes

2022-08-22 07:54 UTC, srehaider commented on profiles/templates/profiles/login.html
> +	<style>
Extract CSS into a separate file.

2022-08-22 07:54 UTC, srehaider commented on profiles/templates/profiles/login.html
> +                        {% csrf_token %}
Use proper indentation, use spaces instead of tabs

2022-08-22 07:54 UTC, srehaider commented on profiles/templates/profiles/register.html
> +    </script>
I think you can achieve it without JavaScript.

2022-08-22 07:54 UTC, srehaider commented on profiles/views.py
> +    return render(request, "profiles/index.html")
What is the purpose of this view?

2022-08-22 07:54 UTC, srehaider commented on profiles/views.py
> +def register_page(request):
```suggestion
def register_user(request):
```

2022-08-22 07:54 UTC, srehaider commented on profiles/views.py
> +    form = CreateUserForm()
```suggestion
```

2022-08-22 07:54 UTC, srehaider commented on profiles/views.py
> +    context = {"form":form}
```suggestion
    context = {"form": CreateUserForm()}
```

2022-08-22 07:54 UTC, srehaider commented on profiles/views.py
> +def login_page(request):
```suggestion
def login_user(request):
```

2022-08-22 07:54 UTC, srehaider commented on profiles/views.py
> +            messages.info(request, "Username or Password is incorrect")
```suggestion
        if user is not None:
            login(request, user)
            return redirect("profiles/index", context)

        messages.info(request, "Username or Password is incorrect")
```

2022-08-22 09:36 UTC, musanaeem commented on profiles/templates/profiles/login.html
> +	<style>
done

2022-08-22 09:36 UTC, musanaeem commented on profiles/templates/profiles/login.html
> +                        {% csrf_token %}
done

2022-08-22 09:36 UTC, musanaeem commented on profiles/templates/profiles/register.html
> +    </script>
done in python

2022-08-22 09:37 UTC, musanaeem commented on profiles/views.py
> +    return render(request, "profiles/index.html")
This view was to show a page after login. Right now, in the latest version, this view is responsible for posting data to Bio database and querying from it too

2022-08-22 09:37 UTC, musanaeem commented on profiles/views.py
> +def register_page(request):
done

2022-08-22 09:38 UTC, musanaeem commented on profiles/views.py
> +    form = CreateUserForm()
Code updated so would need this instantiation. Please review again and let me know if it still needs to be removed

2022-08-22 09:38 UTC, musanaeem commented on profiles/views.py
> +def login_page(request):
done

2022-08-22 09:38 UTC, musanaeem commented on profiles/views.py
> +            messages.info(request, "Username or Password is incorrect")
done

2022-08-23 06:16 UTC, srehaider requested changes
Can you please remove the `.DS_Store` files and add them to the `.gitignore` file?

2022-08-23 06:16 UTC, srehaider commented on profiles/static/styles/login.css
> +    }
You can extract common styles to a separate file so you don't need to repeat them in each file.

2022-08-23 06:16 UTC, srehaider commented on profiles/static/styles/login.css
> +    .user_card {
A general convention is class names have hyphens(`-`) in their names and ids have underscores(`_`) in their names. Change all class names and ids accordingly.
```suggestion
    .user-card {
```

2022-08-23 06:16 UTC, srehaider commented on profiles/static/styles/login.css
> +    }
Always prefer to use classes to style components and ids to uniquely identify elements because two elements shouldn't have the same ids. Styling based on ids increases [specificity](https://css-tricks.com/specifics-on-css-specificity/) which makes it really difficult to override styles.

2022-08-23 06:16 UTC, srehaider commented on profiles/templates/profiles/login.html
> +          <p id="messages"> {{message}} </p>
Still not indented properly.

2022-08-23 06:16 UTC, srehaider commented on profiles/views.py
> +    form = CreateUserForm()
You don't need this initialization here if you are going to return at line# 36 then this initialization is useless.

2022-08-23 08:27 UTC, musanaeem commented on profiles/templates/profiles/login.html
> +          <p id="messages"> {{message}} </p>
I have indented with double space instead of tabs. Would you like me to make it single spaced or is something else the problem?

2022-08-24 05:58 UTC, srehaider requested changes
`.DS_Store` files still have not been removed.

2022-08-24 05:58 UTC, srehaider commented on profiles/static/styles/base.css
> +    }
Please indent all CSS files properly.

2022-08-24 05:58 UTC, srehaider commented on profiles/static/styles/login.css
> +    #messages{
Why do we need to style it based on Id?

2022-08-24 05:58 UTC, srehaider commented on profiles/static/styles/register.css
> +    margin-bottom: auto;
I don't think these properties are required.

2022-08-24 05:58 UTC, srehaider commented on profiles/static/styles/register.css
> +    color: white !important;
Using `!important` is not encouraged, if you can't achieve desired results without it you may need to change base styles. Remove `!important` from all places.

2022-08-24 05:58 UTC, srehaider commented on profiles/templates/profiles/login.html
> +  {% load static %}
It's better to move this statement to the start of the file.

2022-08-24 05:58 UTC, srehaider commented on profiles/templates/profiles/login.html
> +            {% csrf_token %}
Do you know why we use `csrf_token`?

2022-08-24 05:58 UTC, srehaider commented on profiles/templates/profiles/login.html
> +        <div class="mt-4">
You are using mixed tabs and spaces, configure your IDE to display hidden characters(spaces, tabs, line feeds)
```suggestion
          </form>

	</div>
		
        {% for message in messages %}
          <p id="messages"> {{message}} </p>
        {% endfor %}

        <div class="mt-4">
```

2022-08-24 05:58 UTC, srehaider commented on profiles/views.py
> +    }
```suggestion
    context = {
        "users":all_user_data,
        "form":form
    }
```

2022-08-24 05:58 UTC, srehaider commented on profiles/views.py
> +    context = {"form":form}
```suggestion
    context = {"form": form}
```

2022-08-24 07:33 UTC, musanaeem commented on profiles/templates/profiles/login.html
> +            {% csrf_token %}
A cross site request forgery makes sure that even if (after deployment) the url of certain post request sites (such as password changing) are copied by another person/user and opened, the request sent by them will not be accepted for the original user as cross site requests are not approved. Furthermore, CSRF tokens is also how user sessions are checked so if a user ordered a lot of things online and we want to track that back to the user's account, we would check the user's CSRF token and the data associated to that.

2022-08-24 10:30 UTC, srehaider reviewed
Much better :+1: 
Please get rid of the `.DS_Store` files.

2022-08-24 10:30 UTC, srehaider commented on profiles/.gitignore
> +# Byte-compiled / optimized / DLL files
One `.gitignore` at root should be enough, do we really need it?

2022-08-24 10:30 UTC, srehaider commented on profiles/static/styles/base.css
> +    }
```suggestion
body,
html {
    margin: 0;
    padding: 0;
    height: 100%;
    background: #7abecc;
}
```

2022-08-24 11:10 UTC, srehaider approved these changes
:tada:

2022-08-24 11:14 UTC, merged